# POSTGRES
spring.datasource.url=jdbc:postgresql://localhost:5432/order_management_db
spring.datasource.username=usuarioApi_app
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
