# Configuração do R2DBC para PostgreSQL
spring.r2dbc.url=${R2DBC_URL}
spring.r2dbc.username=${R2DBC_USERNAME}
spring.r2dbc.password=${R2DBC_PASSWORD}

# Configuração do Consumer
spring.kafka.consumer.bootstrap-servers=${KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=${KAFKA_CONSUMER_AUTO_OFFSET_RESET}
spring.kafka.consumer.key-deserializer=${KAFKA_CONSUMER_KEY_DESERIALIZER}
spring.kafka.consumer.value-deserializer=${KAFKA_CONSUMER_VALUE_DESERIALIZER}
log.retention.hours=72
log.retention.bytes=1073741824 # Limite de 1 GB por partição


# Configuração do Producer
spring.kafka.producer.bootstrap-servers=${KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=${KAFKA_PRODUCER_KEY_SERIALIZER}
spring.kafka.producer.value-serializer=${KAFKA_PRODUCER_VALUE_SERIALIZER}

# Outras propriedades
spring.kafka.listener.missing-topics-fatal=${KAFKA_LISTENER_MISSING_TOPICS_FATAL}
